services:
  - type: web
    name: realestate
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: realestate-db
          property: connectionString

databases:
  - name: realestate-db
    databaseName: realestate
    user: realestate_user 