"""Add OAuth fields to User

Revision ID: 04b272598b43
Revises:
Create Date: 2025-08-22 13:35:32.031369

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "04b272598b43"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("google_sub", sa.String(length=255), nullable=True)
        )
        batch_op.add_column(
            sa.Column("avatar_url", sa.String(length=500), nullable=True)
        )
        batch_op.add_column(sa.Column("last_login", sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint("uq_user_google_sub", ["google_sub"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_google_sub", type_="unique")
        batch_op.drop_column("last_login")
        batch_op.drop_column("avatar_url")
        batch_op.drop_column("google_sub")

    # ### end Alembic commands ###
